### ISSUE TITLE
Screen capture of images doesn't work on a real device

### ISSUE THREAD

**Issue by Amankumar1947** [shvul/PrivateImage#1]
Tried this on a real device. So I have a use case where I need to switch between enabling and disabling screen capture as I need to take a screenshot programatically. Since it's a AVBufferLayer screenshots of images are empty.

**Comment by shvul** [comment]
Hey @Amankumar1947. That's basically a purpose of the package. It removes target frames from screenshots and prevents screen capture to be started. That's a system behaviour of the DRM protection, so we don't have much to do with it
